#! perl

use PerlApps::Bench;

use PerlApps::Bench::App::PerlCritic;

use Scriptalicious;

my (@perl, $times);
getopt( "perl=s" => \@perl, "times=i", \$times );

my @perl_infos = map { PerlApps::Bench::extract_perl_setup($_) } @perl;

my $result = PerlApps::Bench::run_benchmark( perl => \@perl_infos,
                                             times => $times,
                                             benchmarks => 'PerlApps::Bench::App::PerlCritic',
                                         );

print PerlApps::Bench::report_from_result($result);
